---
title: Voeg een geluid toe aan een sprite of het Speelveld
hero_image: images/banner.png
description: Voeg een geluid toe aan een sprite of het Speelveld.
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: Voeg een geluid toe aan een sprite of het Speelveld
