---
title: Füge einer Figur oder der Bühne einen Klang hinzu
hero_image: images/banner.png
description: Füge einer Figur oder der Bühne einen Klang hinzu
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Füge einer Figur oder der Bühne einen Klang hinzu
