---
title: Adicione um som a um ator ou ao Palco
hero_image: images/banner.png
description: Adicione um som a um ator ou ao Palco
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Adicione um som a um ator ou um Palco
