---
title: Agregar un sonido a un objeto o al Escenario
hero_image: images/banner.png
description: Agregar un sonido a un objeto o al Escenario
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Agregar un sonido a un objeto o al Escenario
