---
title: Lägg till ett ljud till en sprajt eller scenen
hero_image: images/banner.png
description: Lägg till ett ljud till en sprajt eller scenen
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: Lägg till ett ljud till en sprajt eller scenen
