---
title: Ajouter un son à un sprite ou à la scène
hero_image: images/banner.png
description: Ajouter un son à un sprite ou à la scène.
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: Ajouter un son à un sprite ou à la scène
