---
title: Aggiungi un suono a uno sprite o allo Stage
hero_image: images/banner.png
description: Aggiungi un suono a uno sprite o allo Stage
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Aggiungi un suono a uno sprite o allo Stage
